"%dev":
  database:
    table: dev-tasksTable
  quarkus:
    dynamodb:
      endpoint-override: 'http://host.docker.internal:8000'
      aws:
        region: us-east-2
        credentials:
          type: static
          static-provider:
            access-key-id: test-key
            secret-access-key: test-secret

"%test":
  quarkus:
    lambda:
      enable-polling-jvm-mode: true
    log:
      level: DEBUG
    datasource:
      db-kind: mysql
      jdbc:
        driver: org.testcontainers.jdbc.ContainerDatabaseDriver
        url: jdbc:tc:mysql:latest:///test_product_database
      password: admin
      username: admin
    hibernate-orm:
      database:
        generation: none
      sql-load-script: db/test/init-schema.sql

