"%dev":
  database:
    table: dev-tasksTable
  quarkus:
    dynamodb:
      endpoint-override: 'http://host.docker.internal:8000'
      aws:
        region: us-east-2
        credentials:
          type: static
          static-provider:
            access-key-id: test-key
            secret-access-key: test-secret

"%test":
  quarkus:
    lambda:
      enable-polling-jvm-mode: true
    log:
      level: DEBUG
    datasource:
      db-kind: mysql
      jdbc:
        url: jdbc:tc:mysql:latest:///database
    hibernate-orm:
      database:
        generation: create-drop
        # quarkus.datasource.jdbc.max-size=8
        #quarkus.datasource.jdbc.min-size=2
      #sql-load-script: db/test/init-schema.sql

